on:
  workflow_call:
    secrets:
      OF_REGISTRY_HOST:
        required: true
      OF_REGISTRY_TOKEN:
        required: true

name: Run pnpm test and lint
env:
  HUSKY: 0

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Outfunnel Registry
      run: |
        echo "" >> .npmrc
        echo "@outfunnel:registry=https://${{ secrets.OF_REGISTRY_HOST }}/" >> .npmrc
        echo "//${{ secrets.OF_REGISTRY_HOST }}/:_authToken=${{ secrets.OF_REGISTRY_TOKEN }}" >> .npmrc

    - name: Read .nvmrc
      run: echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_OUTPUT
      id: nvm

    - name: Setup pnpm
      uses: pnpm/action-setup@v4

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: '${{ steps.nvm.outputs.NVMRC }}'

    - run: pnpm install --frozen-lockfile
    - run: pnpm run lint --if-present
    - run: pnpm run build --if-present
    - run: pnpm test --if-present
